/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "211f3b4785096f876f2d96c7ca931ede27919c9f"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
